### ISSUE TITLE
Leaf might be broken?

### ISSUE THREAD

**Issue by jhoughjr** [vaporberlin/basic-auth-with-session#1]
pulled bait and ran.

The current hash key "0000000000000000" is not secure.
Update hash.key in Config/crypto.json before using in production.
Use `openssl rand -base64 <length>` to generate a random string.
The current cipher key "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" is not secure.
Update cipher.key in Config/crypto.json before using in production.
Use `openssl rand -base64 32` to generate a random string.
Database prepared
No command supplied, defaulting to serve...
Starting server on 0.0.0.0:8008
GET /
GET /favicon.ico
[Abort request error: Not Found] [Identifier: Vapor.Abort.notFound]

**Comment by MartinLasek** [comment]
All lines until `Starting server on 0.0.0.0:8008` are only warnings and can be ignored for this 😊 

Afterwards it seems like you tried to access `127.0.0.1:8008/` but this project didn't define anything at this route. Have you tried to access `127.0.0.1:8008/login` 😊 ?

**Comment by MartinLasek** [comment]
I am happy to hear that 😊 !
I'd be glad to try your product once it's finished. Rock it 🚀 !
